fix: include authorize screen
hvhallmann/nullstack-oauth pull request #15
Opened 2022-01-24 19:00 UTC by hvhallmann

2022-01-24 19:59 UTC, jayremias requested changes

2022-01-24 19:59 UTC, jayremias commented on src/pages/oauth/ClientAuthentication.njs
> +        <br />
Best to apply margin in here instead of `<br>`. You can use `mb-4` in the above div

2022-01-25 00:07 UTC, hvhallmann commented
fixed

2022-01-25 12:29 UTC, merged

2022-01-26 13:10 UTC, jayremias reviewed
look good

2022-01-26 13:10 UTC, jayremias commented on src/pages/oauth/ClientAuthentication.njs
> +                <input type="checkbox" name="check_wallet" bind={this.read_wallet_address} />
We need to create components here. But lets change when we move to the main repo